# Generated by Django 4.1 on 2022-09-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizaaModel',
            new_name='PizzaModel',
        ),
    ]
